<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arbitro_planilla extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Arbitro_planilla_model');
    } 

    /*
     * Listing of arbitro_planilla
     */
    function index()
    {
        $data['arbitro_planilla'] = $this->Arbitro_planilla_model->get_all_arbitro_planilla();
        
        $data['_view'] = 'arbitro_planilla/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new arbitro_planilla
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipo_juez' => $this->input->post('tipo_juez'),
            );
            
            $arbitro_planilla_id = $this->Arbitro_planilla_model->add_arbitro_planilla($params);
            redirect('arbitro_planilla/index');
        }
        else
        {            
            $data['_view'] = 'arbitro_planilla/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a arbitro_planilla
     */
    function edit($id_arbitro)
    {   
        // check if the arbitro_planilla exists before trying to edit it
        $data['arbitro_planilla'] = $this->Arbitro_planilla_model->get_arbitro_planilla($id_arbitro);
        
        if(isset($data['arbitro_planilla']['id_arbitro']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipo_juez' => $this->input->post('tipo_juez'),
                );

                $this->Arbitro_planilla_model->update_arbitro_planilla($id_arbitro,$params);            
                redirect('arbitro_planilla/index');
            }
            else
            {
                $data['_view'] = 'arbitro_planilla/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The arbitro_planilla you are trying to edit does not exist.');
    } 

    /*
     * Deleting arbitro_planilla
     */
    function remove($id_arbitro)
    {
        $arbitro_planilla = $this->Arbitro_planilla_model->get_arbitro_planilla($id_arbitro);

        // check if the arbitro_planilla exists before trying to delete it
        if(isset($arbitro_planilla['id_arbitro']))
        {
            $this->Arbitro_planilla_model->delete_arbitro_planilla($id_arbitro);
            redirect('arbitro_planilla/index');
        }
        else
            show_error('The arbitro_planilla you are trying to delete does not exist.');
    }
    
}
