<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arbitro extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Arbitro_model');
    } 

    /*
     * Listing of arbitro
     */
    function index()
    {
        $data['arbitro'] = $this->Arbitro_model->get_all_arbitro();
        
        $data['_view'] = 'arbitro/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new arbitro
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_inf' => $this->input->post('id_inf'),
				'estado_arbitro' => $this->input->post('estado_arbitro'),
            );
            
            $arbitro_id = $this->Arbitro_model->add_arbitro($params);
            redirect('arbitro/index');
        }
        else
        {            
            $data['_view'] = 'arbitro/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a arbitro
     */
    function edit($id_arbitro)
    {   
        // check if the arbitro exists before trying to edit it
        $data['arbitro'] = $this->Arbitro_model->get_arbitro($id_arbitro);
        
        if(isset($data['arbitro']['id_arbitro']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_inf' => $this->input->post('id_inf'),
					'estado_arbitro' => $this->input->post('estado_arbitro'),
                );

                $this->Arbitro_model->update_arbitro($id_arbitro,$params);            
                redirect('arbitro/index');
            }
            else
            {
                $data['_view'] = 'arbitro/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The arbitro you are trying to edit does not exist.');
    } 

    /*
     * Deleting arbitro
     */
    function remove($id_arbitro)
    {
        $arbitro = $this->Arbitro_model->get_arbitro($id_arbitro);

        // check if the arbitro exists before trying to delete it
        if(isset($arbitro['id_arbitro']))
        {
            $this->Arbitro_model->delete_arbitro($id_arbitro);
            redirect('arbitro/index');
        }
        else
            show_error('The arbitro you are trying to delete does not exist.');
    }
    
}
