<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Club_deportivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Club_deportivo_model');
    } 

    /*
     * Listing of club_deportivo
     */
    function index()
    {
        $data['club_deportivo'] = $this->Club_deportivo_model->get_all_club_deportivo();
        
        $data['_view'] = 'club_deportivo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new club_deportivo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre_club' => $this->input->post('nombre_club'),
				'fundacion_club' => $this->input->post('fundacion_club'),
				'telef_club' => $this->input->post('telef_club'),
				'estado_club' => $this->input->post('estado_club'),
				'direccion_club' => $this->input->post('direccion_club'),
            );
            
            $club_deportivo_id = $this->Club_deportivo_model->add_club_deportivo($params);
            redirect('club_deportivo/index');
        }
        else
        {            
            $data['_view'] = 'club_deportivo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a club_deportivo
     */
    function edit($id_club)
    {   
        // check if the club_deportivo exists before trying to edit it
        $data['club_deportivo'] = $this->Club_deportivo_model->get_club_deportivo($id_club);
        
        if(isset($data['club_deportivo']['id_club']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre_club' => $this->input->post('nombre_club'),
					'fundacion_club' => $this->input->post('fundacion_club'),
					'telef_club' => $this->input->post('telef_club'),
					'estado_club' => $this->input->post('estado_club'),
					'direccion_club' => $this->input->post('direccion_club'),
                );

                $this->Club_deportivo_model->update_club_deportivo($id_club,$params);            
                redirect('club_deportivo/index');
            }
            else
            {
                $data['_view'] = 'club_deportivo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The club_deportivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting club_deportivo
     */
    function remove($id_club)
    {
        $club_deportivo = $this->Club_deportivo_model->get_club_deportivo($id_club);

        // check if the club_deportivo exists before trying to delete it
        if(isset($club_deportivo['id_club']))
        {
            $this->Club_deportivo_model->delete_club_deportivo($id_club);
            redirect('club_deportivo/index');
        }
        else
            show_error('The club_deportivo you are trying to delete does not exist.');
    }
    
}
