<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrenador_equipo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entrenador_equipo_model');
    } 

    /*
     * Listing of entrenador_equipo
     */
    function index()
    {
        $data['entrenador_equipo'] = $this->Entrenador_equipo_model->get_all_entrenador_equipo();
        
        $data['_view'] = 'entrenador_equipo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new entrenador_equipo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'desde_ent_equ' => $this->input->post('desde_ent_equ'),
				'hasta_ent_equ' => $this->input->post('hasta_ent_equ'),
				'estado_ent_equ' => $this->input->post('estado_ent_equ'),
            );
            
            $entrenador_equipo_id = $this->Entrenador_equipo_model->add_entrenador_equipo($params);
            redirect('entrenador_equipo/index');
        }
        else
        {            
            $data['_view'] = 'entrenador_equipo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a entrenador_equipo
     */
    function edit($id_equipo)
    {   
        // check if the entrenador_equipo exists before trying to edit it
        $data['entrenador_equipo'] = $this->Entrenador_equipo_model->get_entrenador_equipo($id_equipo);
        
        if(isset($data['entrenador_equipo']['id_equipo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'desde_ent_equ' => $this->input->post('desde_ent_equ'),
					'hasta_ent_equ' => $this->input->post('hasta_ent_equ'),
					'estado_ent_equ' => $this->input->post('estado_ent_equ'),
                );

                $this->Entrenador_equipo_model->update_entrenador_equipo($id_equipo,$params);            
                redirect('entrenador_equipo/index');
            }
            else
            {
                $data['_view'] = 'entrenador_equipo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The entrenador_equipo you are trying to edit does not exist.');
    } 

    /*
     * Deleting entrenador_equipo
     */
    function remove($id_equipo)
    {
        $entrenador_equipo = $this->Entrenador_equipo_model->get_entrenador_equipo($id_equipo);

        // check if the entrenador_equipo exists before trying to delete it
        if(isset($entrenador_equipo['id_equipo']))
        {
            $this->Entrenador_equipo_model->delete_entrenador_equipo($id_equipo);
            redirect('entrenador_equipo/index');
        }
        else
            show_error('The entrenador_equipo you are trying to delete does not exist.');
    }
    
}
