<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrenador extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entrenador_model');
    } 

    /*
     * Listing of entrenador
     */
    function index()
    {
        $data['entrenador'] = $this->Entrenador_model->get_all_entrenador();
        
        $data['_view'] = 'entrenador/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new entrenador
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $entrenador_id = $this->Entrenador_model->add_entrenador($params);
            redirect('entrenador/index');
        }
        else
        {            
            $data['_view'] = 'entrenador/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a entrenador
     */
    function edit($id_entrenador)
    {   
        // check if the entrenador exists before trying to edit it
        $data['entrenador'] = $this->Entrenador_model->get_entrenador($id_entrenador);
        
        if(isset($data['entrenador']['id_entrenador']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Entrenador_model->update_entrenador($id_entrenador,$params);            
                redirect('entrenador/index');
            }
            else
            {
                $data['_view'] = 'entrenador/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The entrenador you are trying to edit does not exist.');
    } 

    /*
     * Deleting entrenador
     */
    function remove($id_entrenador)
    {
        $entrenador = $this->Entrenador_model->get_entrenador($id_entrenador);

        // check if the entrenador exists before trying to delete it
        if(isset($entrenador['id_entrenador']))
        {
            $this->Entrenador_model->delete_entrenador($id_entrenador);
            redirect('entrenador/index');
        }
        else
            show_error('The entrenador you are trying to delete does not exist.');
    }
    
}
