<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipo_jugador extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Equipo_jugador_model');
    } 

    /*
     * Listing of equipo_jugador
     */
    function index()
    {
        $data['equipo_jugador'] = $this->Equipo_jugador_model->get_all_equipo_jugador();
        
        $data['_view'] = 'equipo_jugador/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new equipo_jugador
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_jug' => $this->input->post('id_jug'),
				'id_equipo' => $this->input->post('id_equipo'),
				'desde_equ_jug' => $this->input->post('desde_equ_jug'),
				'hasta_equ_jug' => $this->input->post('hasta_equ_jug'),
				'estado_jug_equipo' => $this->input->post('estado_jug_equipo'),
				'obs_equ_jug' => $this->input->post('obs_equ_jug'),
            );
            
            $equipo_jugador_id = $this->Equipo_jugador_model->add_equipo_jugador($params);
            redirect('equipo_jugador/index');
        }
        else
        {            
            $data['_view'] = 'equipo_jugador/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a equipo_jugador
     */
    function edit($id_jug_equipo)
    {   
        // check if the equipo_jugador exists before trying to edit it
        $data['equipo_jugador'] = $this->Equipo_jugador_model->get_equipo_jugador($id_jug_equipo);
        
        if(isset($data['equipo_jugador']['id_jug_equipo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_jug' => $this->input->post('id_jug'),
					'id_equipo' => $this->input->post('id_equipo'),
					'desde_equ_jug' => $this->input->post('desde_equ_jug'),
					'hasta_equ_jug' => $this->input->post('hasta_equ_jug'),
					'estado_jug_equipo' => $this->input->post('estado_jug_equipo'),
					'obs_equ_jug' => $this->input->post('obs_equ_jug'),
                );

                $this->Equipo_jugador_model->update_equipo_jugador($id_jug_equipo,$params);            
                redirect('equipo_jugador/index');
            }
            else
            {
                $data['_view'] = 'equipo_jugador/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The equipo_jugador you are trying to edit does not exist.');
    } 

    /*
     * Deleting equipo_jugador
     */
    function remove($id_jug_equipo)
    {
        $equipo_jugador = $this->Equipo_jugador_model->get_equipo_jugador($id_jug_equipo);

        // check if the equipo_jugador exists before trying to delete it
        if(isset($equipo_jugador['id_jug_equipo']))
        {
            $this->Equipo_jugador_model->delete_equipo_jugador($id_jug_equipo);
            redirect('equipo_jugador/index');
        }
        else
            show_error('The equipo_jugador you are trying to delete does not exist.');
    }
    
}
