<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fixture extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fixture_model');
    } 

    /*
     * Listing of fixture
     */
    function index()
    {
        $data['fixture'] = $this->Fixture_model->get_all_fixture();
        
        $data['_view'] = 'fixture/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fixture
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_equipo' => $this->input->post('id_equipo'),
				'equ_id_equipo' => $this->input->post('equ_id_equipo'),
				'titulo_fix' => $this->input->post('titulo_fix'),
				'fecha_fix' => $this->input->post('fecha_fix'),
				'estado_fix' => $this->input->post('estado_fix'),
            );
            
            $fixture_id = $this->Fixture_model->add_fixture($params);
            redirect('fixture/index');
        }
        else
        {            
            $data['_view'] = 'fixture/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fixture
     */
    function edit($id_fix)
    {   
        // check if the fixture exists before trying to edit it
        $data['fixture'] = $this->Fixture_model->get_fixture($id_fix);
        
        if(isset($data['fixture']['id_fix']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_equipo' => $this->input->post('id_equipo'),
					'equ_id_equipo' => $this->input->post('equ_id_equipo'),
					'titulo_fix' => $this->input->post('titulo_fix'),
					'fecha_fix' => $this->input->post('fecha_fix'),
					'estado_fix' => $this->input->post('estado_fix'),
                );

                $this->Fixture_model->update_fixture($id_fix,$params);            
                redirect('fixture/index');
            }
            else
            {
                $data['_view'] = 'fixture/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fixture you are trying to edit does not exist.');
    } 

    /*
     * Deleting fixture
     */
    function remove($id_fix)
    {
        $fixture = $this->Fixture_model->get_fixture($id_fix);

        // check if the fixture exists before trying to delete it
        if(isset($fixture['id_fix']))
        {
            $this->Fixture_model->delete_fixture($id_fix);
            redirect('fixture/index');
        }
        else
            show_error('The fixture you are trying to delete does not exist.');
    }
    
}
