<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gestion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gestion_model');
    } 

    /*
     * Listing of gestion
     */
    function index()
    {
        $data['gestion'] = $this->Gestion_model->get_all_gestion();
        
        $data['_view'] = 'gestion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new gestion
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('nombre_gestion','Nombre','trim|required', array('required' => 'Este Campo no debe estar vacio'));
        if($this->form_validation->run())     
        {
            $estado_gestion = "ACTIVO";
            $params = array(
                'nombre_gestion' => $this->input->post('nombre_gestion'),
                'inicio_gestion' => $this->input->post('inicio_gestion'),
                'fin_gestion'    => $this->input->post('fin_gestion'),
                'estado_gestion' => $estado_gestion,
            );
            $gestion_id = $this->Gestion_model->add_gestion($params);
            redirect('gestion/index');
        }
        else
        {            
            $data['_view'] = 'gestion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a gestion
     */
    function edit($id_gestion)
    {   
        // check if the gestion exists before trying to edit it
        $data['gestion'] = $this->Gestion_model->get_gestion($id_gestion);
        
        if(isset($data['gestion']['id_gestion']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nombre_gestion','Nombre','trim|required', array('required' => 'Este Campo no debe estar vacio'));
            if($this->form_validation->run())     
            {
                $params = array(
                    'nombre_gestion' => $this->input->post('nombre_gestion'),
                    'inicio_gestion' => $this->input->post('inicio_gestion'),
                    'fin_gestion'    => $this->input->post('fin_gestion'),
                    'estado_gestion' => $this->input->post('estado_gestion'),
                );
                $this->Gestion_model->update_gestion($id_gestion,$params);            
                redirect('gestion/index');
            }
            else
            {
                $data['_view'] = 'gestion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The gestion you are trying to edit does not exist.');
    } 

    /*
     * Deleting gestion
     */
    /*function remove($id_gestion)
    {
        $gestion = $this->Gestion_model->get_gestion($id_gestion);

        // check if the gestion exists before trying to delete it
        if(isset($gestion['id_gestion']))
        {
            $this->Gestion_model->delete_gestion($id_gestion);
            redirect('gestion/index');
        }
        else
            show_error('The gestion you are trying to delete does not exist.');
    }*/
    
}
