<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inf_personal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Inf_personal_model');
    } 

    /*
     * Listing of inf_personal
     */
    function index()
    {
        $data['inf_personal'] = $this->Inf_personal_model->get_all_inf_personal();
        
        $data['_view'] = 'inf_personal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new inf_personal
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'nombre' => $this->input->post('nombre'),
				'ap_pat' => $this->input->post('ap_pat'),
				'ap_mat' => $this->input->post('ap_mat'),
				'fecha_nac' => $this->input->post('fecha_nac'),
				'sexo' => $this->input->post('sexo'),
				'est_civil' => $this->input->post('est_civil'),
				'ci' => $this->input->post('ci'),
				'foto' => $this->input->post('foto'),
				'direccion' => $this->input->post('direccion'),
            );
            
            $inf_personal_id = $this->Inf_personal_model->add_inf_personal($params);
            redirect('inf_personal/index');
        }
        else
        {            
            $data['_view'] = 'inf_personal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a inf_personal
     */
    function edit($id_inf)
    {   
        // check if the inf_personal exists before trying to edit it
        $data['inf_personal'] = $this->Inf_personal_model->get_inf_personal($id_inf);
        
        if(isset($data['inf_personal']['id_inf']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'nombre' => $this->input->post('nombre'),
					'ap_pat' => $this->input->post('ap_pat'),
					'ap_mat' => $this->input->post('ap_mat'),
					'fecha_nac' => $this->input->post('fecha_nac'),
					'sexo' => $this->input->post('sexo'),
					'est_civil' => $this->input->post('est_civil'),
					'ci' => $this->input->post('ci'),
					'foto' => $this->input->post('foto'),
					'direccion' => $this->input->post('direccion'),
                );

                $this->Inf_personal_model->update_inf_personal($id_inf,$params);            
                redirect('inf_personal/index');
            }
            else
            {
                $data['_view'] = 'inf_personal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The inf_personal you are trying to edit does not exist.');
    } 

    /*
     * Deleting inf_personal
     */
    function remove($id_inf)
    {
        $inf_personal = $this->Inf_personal_model->get_inf_personal($id_inf);

        // check if the inf_personal exists before trying to delete it
        if(isset($inf_personal['id_inf']))
        {
            $this->Inf_personal_model->delete_inf_personal($id_inf);
            redirect('inf_personal/index');
        }
        else
            show_error('The inf_personal you are trying to delete does not exist.');
    }
    
}
