<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jugador extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jugador_model');
    } 

    /*
     * Listing of jugador
     */
    function index()
    {
        $data['jugador'] = $this->Jugador_model->get_all_jugador();
        
        $data['_view'] = 'jugador/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jugador
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_inf' => $this->input->post('id_inf'),
				'posicion_jug' => $this->input->post('posicion_jug'),
            );
            
            $jugador_id = $this->Jugador_model->add_jugador($params);
            redirect('jugador/index');
        }
        else
        {            
            $data['_view'] = 'jugador/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jugador
     */
    function edit($id_jug)
    {   
        // check if the jugador exists before trying to edit it
        $data['jugador'] = $this->Jugador_model->get_jugador($id_jug);
        
        if(isset($data['jugador']['id_jug']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_inf' => $this->input->post('id_inf'),
					'posicion_jug' => $this->input->post('posicion_jug'),
                );

                $this->Jugador_model->update_jugador($id_jug,$params);            
                redirect('jugador/index');
            }
            else
            {
                $data['_view'] = 'jugador/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jugador you are trying to edit does not exist.');
    } 

    /*
     * Deleting jugador
     */
    function remove($id_jug)
    {
        $jugador = $this->Jugador_model->get_jugador($id_jug);

        // check if the jugador exists before trying to delete it
        if(isset($jugador['id_jug']))
        {
            $this->Jugador_model->delete_jugador($id_jug);
            redirect('jugador/index');
        }
        else
            show_error('The jugador you are trying to delete does not exist.');
    }
    
}
