<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jugador_planilla extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jugador_planilla_model');
    } 

    /*
     * Listing of jugador_planilla
     */
    function index()
    {
        $data['jugador_planilla'] = $this->Jugador_planilla_model->get_all_jugador_planilla();
        
        $data['_view'] = 'jugador_planilla/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jugador_planilla
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jugador' => $this->input->post('jugador'),
				'arquero' => $this->input->post('arquero'),
				'capitan' => $this->input->post('capitan'),
				'id_plan' => $this->input->post('id_plan'),
				'id_jug' => $this->input->post('id_jug'),
				'num_casaca' => $this->input->post('num_casaca'),
				'gol' => $this->input->post('gol'),
            );
            
            $jugador_planilla_id = $this->Jugador_planilla_model->add_jugador_planilla($params);
            redirect('jugador_planilla/index');
        }
        else
        {            
            $data['_view'] = 'jugador_planilla/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jugador_planilla
     */
    function edit($id_jugador_planilla)
    {   
        // check if the jugador_planilla exists before trying to edit it
        $data['jugador_planilla'] = $this->Jugador_planilla_model->get_jugador_planilla($id_jugador_planilla);
        
        if(isset($data['jugador_planilla']['id_jugador_planilla']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jugador' => $this->input->post('jugador'),
					'arquero' => $this->input->post('arquero'),
					'capitan' => $this->input->post('capitan'),
					'id_plan' => $this->input->post('id_plan'),
					'id_jug' => $this->input->post('id_jug'),
					'num_casaca' => $this->input->post('num_casaca'),
					'gol' => $this->input->post('gol'),
                );

                $this->Jugador_planilla_model->update_jugador_planilla($id_jugador_planilla,$params);            
                redirect('jugador_planilla/index');
            }
            else
            {
                $data['_view'] = 'jugador_planilla/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jugador_planilla you are trying to edit does not exist.');
    } 

    /*
     * Deleting jugador_planilla
     */
    function remove($id_jugador_planilla)
    {
        $jugador_planilla = $this->Jugador_planilla_model->get_jugador_planilla($id_jugador_planilla);

        // check if the jugador_planilla exists before trying to delete it
        if(isset($jugador_planilla['id_jugador_planilla']))
        {
            $this->Jugador_planilla_model->delete_jugador_planilla($id_jugador_planilla);
            redirect('jugador_planilla/index');
        }
        else
            show_error('The jugador_planilla you are trying to delete does not exist.');
    }
    
}
