<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Memorandum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Memorandum_model');
    } 

    /*
     * Listing of memorandum
     */
    function index()
    {
        $data['memorandum'] = $this->Memorandum_model->get_all_memorandum();
        
        $data['_view'] = 'memorandum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new memorandum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_jug' => $this->input->post('id_jug'),
				'id_equipo' => $this->input->post('id_equipo'),
				'titulo_memo' => $this->input->post('titulo_memo'),
				'inicio_memo' => $this->input->post('inicio_memo'),
				'fin_memo' => $this->input->post('fin_memo'),
				'estado_memo' => $this->input->post('estado_memo'),
				'detalle_memo' => $this->input->post('detalle_memo'),
            );
            
            $memorandum_id = $this->Memorandum_model->add_memorandum($params);
            redirect('memorandum/index');
        }
        else
        {            
            $data['_view'] = 'memorandum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a memorandum
     */
    function edit($id_memo)
    {   
        // check if the memorandum exists before trying to edit it
        $data['memorandum'] = $this->Memorandum_model->get_memorandum($id_memo);
        
        if(isset($data['memorandum']['id_memo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_jug' => $this->input->post('id_jug'),
					'id_equipo' => $this->input->post('id_equipo'),
					'titulo_memo' => $this->input->post('titulo_memo'),
					'inicio_memo' => $this->input->post('inicio_memo'),
					'fin_memo' => $this->input->post('fin_memo'),
					'estado_memo' => $this->input->post('estado_memo'),
					'detalle_memo' => $this->input->post('detalle_memo'),
                );

                $this->Memorandum_model->update_memorandum($id_memo,$params);            
                redirect('memorandum/index');
            }
            else
            {
                $data['_view'] = 'memorandum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The memorandum you are trying to edit does not exist.');
    } 

    /*
     * Deleting memorandum
     */
    function remove($id_memo)
    {
        $memorandum = $this->Memorandum_model->get_memorandum($id_memo);

        // check if the memorandum exists before trying to delete it
        if(isset($memorandum['id_memo']))
        {
            $this->Memorandum_model->delete_memorandum($id_memo);
            redirect('memorandum/index');
        }
        else
            show_error('The memorandum you are trying to delete does not exist.');
    }
    
}
