<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa_directiva extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mesa_directiva_model');
    } 

    /*
     * Listing of mesa_directiva
     */
    function index()
    {
        $data['mesa_directiva'] = $this->Mesa_directiva_model->get_all_mesa_directiva();
        
        $data['_view'] = 'mesa_directiva/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mesa_directiva
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_camp' => $this->input->post('id_camp'),
				'id_inf' => $this->input->post('id_inf'),
				'id_club' => $this->input->post('id_club'),
				'cargo_mesa' => $this->input->post('cargo_mesa'),
				'estado_mesa' => $this->input->post('estado_mesa'),
				'ini_mesa' => $this->input->post('ini_mesa'),
				'fin_mesa' => $this->input->post('fin_mesa'),
            );
            
            $mesa_directiva_id = $this->Mesa_directiva_model->add_mesa_directiva($params);
            redirect('mesa_directiva/index');
        }
        else
        {            
            $data['_view'] = 'mesa_directiva/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mesa_directiva
     */
    function edit($id_mesa)
    {   
        // check if the mesa_directiva exists before trying to edit it
        $data['mesa_directiva'] = $this->Mesa_directiva_model->get_mesa_directiva($id_mesa);
        
        if(isset($data['mesa_directiva']['id_mesa']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_camp' => $this->input->post('id_camp'),
					'id_inf' => $this->input->post('id_inf'),
					'id_club' => $this->input->post('id_club'),
					'cargo_mesa' => $this->input->post('cargo_mesa'),
					'estado_mesa' => $this->input->post('estado_mesa'),
					'ini_mesa' => $this->input->post('ini_mesa'),
					'fin_mesa' => $this->input->post('fin_mesa'),
                );

                $this->Mesa_directiva_model->update_mesa_directiva($id_mesa,$params);            
                redirect('mesa_directiva/index');
            }
            else
            {
                $data['_view'] = 'mesa_directiva/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mesa_directiva you are trying to edit does not exist.');
    } 

    /*
     * Deleting mesa_directiva
     */
    function remove($id_mesa)
    {
        $mesa_directiva = $this->Mesa_directiva_model->get_mesa_directiva($id_mesa);

        // check if the mesa_directiva exists before trying to delete it
        if(isset($mesa_directiva['id_mesa']))
        {
            $this->Mesa_directiva_model->delete_mesa_directiva($id_mesa);
            redirect('mesa_directiva/index');
        }
        else
            show_error('The mesa_directiva you are trying to delete does not exist.');
    }
    
}
