<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Movimiento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Movimiento_model');
    } 

    /*
     * Listing of movimiento
     */
    function index()
    {
        $data['movimiento'] = $this->Movimiento_model->get_all_movimiento();
        
        $data['_view'] = 'movimiento/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new movimiento
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_camp' => $this->input->post('id_camp'),
				'fecha_mov' => $this->input->post('fecha_mov'),
				'tipo_mov' => $this->input->post('tipo_mov'),
				'cant_ingreso' => $this->input->post('cant_ingreso'),
				'cant_egreso' => $this->input->post('cant_egreso'),
				'cant_saldo' => $this->input->post('cant_saldo'),
				'monto_ingreso' => $this->input->post('monto_ingreso'),
				'monto_salida' => $this->input->post('monto_salida'),
				'monto_saldo' => $this->input->post('monto_saldo'),
				'estado_mov' => $this->input->post('estado_mov'),
				'detalle_mov' => $this->input->post('detalle_mov'),
            );
            
            $movimiento_id = $this->Movimiento_model->add_movimiento($params);
            redirect('movimiento/index');
        }
        else
        {            
            $data['_view'] = 'movimiento/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a movimiento
     */
    function edit($id_mov)
    {   
        // check if the movimiento exists before trying to edit it
        $data['movimiento'] = $this->Movimiento_model->get_movimiento($id_mov);
        
        if(isset($data['movimiento']['id_mov']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_camp' => $this->input->post('id_camp'),
					'fecha_mov' => $this->input->post('fecha_mov'),
					'tipo_mov' => $this->input->post('tipo_mov'),
					'cant_ingreso' => $this->input->post('cant_ingreso'),
					'cant_egreso' => $this->input->post('cant_egreso'),
					'cant_saldo' => $this->input->post('cant_saldo'),
					'monto_ingreso' => $this->input->post('monto_ingreso'),
					'monto_salida' => $this->input->post('monto_salida'),
					'monto_saldo' => $this->input->post('monto_saldo'),
					'estado_mov' => $this->input->post('estado_mov'),
					'detalle_mov' => $this->input->post('detalle_mov'),
                );

                $this->Movimiento_model->update_movimiento($id_mov,$params);            
                redirect('movimiento/index');
            }
            else
            {
                $data['_view'] = 'movimiento/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The movimiento you are trying to edit does not exist.');
    } 

    /*
     * Deleting movimiento
     */
    function remove($id_mov)
    {
        $movimiento = $this->Movimiento_model->get_movimiento($id_mov);

        // check if the movimiento exists before trying to delete it
        if(isset($movimiento['id_mov']))
        {
            $this->Movimiento_model->delete_movimiento($id_mov);
            redirect('movimiento/index');
        }
        else
            show_error('The movimiento you are trying to delete does not exist.');
    }
    
}
