<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Noticium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Noticium_model');
    } 

    /*
     * Listing of noticia
     */
    function index()
    {
        $data['noticia'] = $this->Noticium_model->get_all_noticia();
        
        $data['_view'] = 'noticium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new noticium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_camp' => $this->input->post('id_camp'),
				'fecha_ini_not' => $this->input->post('fecha_ini_not'),
				'fecha_fin_not' => $this->input->post('fecha_fin_not'),
				'descripcion_not' => $this->input->post('descripcion_not'),
            );
            
            $noticium_id = $this->Noticium_model->add_noticium($params);
            redirect('noticium/index');
        }
        else
        {            
            $data['_view'] = 'noticium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a noticium
     */
    function edit($id_not)
    {   
        // check if the noticium exists before trying to edit it
        $data['noticium'] = $this->Noticium_model->get_noticium($id_not);
        
        if(isset($data['noticium']['id_not']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_camp' => $this->input->post('id_camp'),
					'fecha_ini_not' => $this->input->post('fecha_ini_not'),
					'fecha_fin_not' => $this->input->post('fecha_fin_not'),
					'descripcion_not' => $this->input->post('descripcion_not'),
                );

                $this->Noticium_model->update_noticium($id_not,$params);            
                redirect('noticium/index');
            }
            else
            {
                $data['_view'] = 'noticium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The noticium you are trying to edit does not exist.');
    } 

    /*
     * Deleting noticium
     */
    function remove($id_not)
    {
        $noticium = $this->Noticium_model->get_noticium($id_not);

        // check if the noticium exists before trying to delete it
        if(isset($noticium['id_not']))
        {
            $this->Noticium_model->delete_noticium($id_not);
            redirect('noticium/index');
        }
        else
            show_error('The noticium you are trying to delete does not exist.');
    }
    
}
