<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Planilla extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Planilla_model');
    } 

    /*
     * Listing of planilla
     */
    function index()
    {
        $data['planilla'] = $this->Planilla_model->get_all_planilla();
        
        $data['_view'] = 'planilla/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new planilla
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_fix' => $this->input->post('id_fix'),
				'equipo1' => $this->input->post('equipo1'),
				'equipo2' => $this->input->post('equipo2'),
				'gol_equipo1' => $this->input->post('gol_equipo1'),
				'gol_equipo2' => $this->input->post('gol_equipo2'),
				'puntos_equipo1' => $this->input->post('puntos_equipo1'),
				'puntos_equipo2' => $this->input->post('puntos_equipo2'),
				'estado_plan' => $this->input->post('estado_plan'),
				'observacion_plan' => $this->input->post('observacion_plan'),
            );
            
            $planilla_id = $this->Planilla_model->add_planilla($params);
            redirect('planilla/index');
        }
        else
        {            
            $data['_view'] = 'planilla/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a planilla
     */
    function edit($id_plan)
    {   
        // check if the planilla exists before trying to edit it
        $data['planilla'] = $this->Planilla_model->get_planilla($id_plan);
        
        if(isset($data['planilla']['id_plan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_fix' => $this->input->post('id_fix'),
					'equipo1' => $this->input->post('equipo1'),
					'equipo2' => $this->input->post('equipo2'),
					'gol_equipo1' => $this->input->post('gol_equipo1'),
					'gol_equipo2' => $this->input->post('gol_equipo2'),
					'puntos_equipo1' => $this->input->post('puntos_equipo1'),
					'puntos_equipo2' => $this->input->post('puntos_equipo2'),
					'estado_plan' => $this->input->post('estado_plan'),
					'observacion_plan' => $this->input->post('observacion_plan'),
                );

                $this->Planilla_model->update_planilla($id_plan,$params);            
                redirect('planilla/index');
            }
            else
            {
                $data['_view'] = 'planilla/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The planilla you are trying to edit does not exist.');
    } 

    /*
     * Deleting planilla
     */
    function remove($id_plan)
    {
        $planilla = $this->Planilla_model->get_planilla($id_plan);

        // check if the planilla exists before trying to delete it
        if(isset($planilla['id_plan']))
        {
            $this->Planilla_model->delete_planilla($id_plan);
            redirect('planilla/index');
        }
        else
            show_error('The planilla you are trying to delete does not exist.');
    }
    
}
