<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Premio extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Premio_model');
    } 

    /*
     * Listing of premio
     */
    function index()
    {
        $data['premio'] = $this->Premio_model->get_all_premio();
        
        $data['_view'] = 'premio/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new premio
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_camp' => $this->input->post('id_camp'),
				'id_equipo' => $this->input->post('id_equipo'),
				'nombre_premio' => $this->input->post('nombre_premio'),
				'costo_premio' => $this->input->post('costo_premio'),
				'detalle_premio' => $this->input->post('detalle_premio'),
				'estado_premio' => $this->input->post('estado_premio'),
            );
            
            $premio_id = $this->Premio_model->add_premio($params);
            redirect('premio/index');
        }
        else
        {            
            $data['_view'] = 'premio/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a premio
     */
    function edit($id_premio)
    {   
        // check if the premio exists before trying to edit it
        $data['premio'] = $this->Premio_model->get_premio($id_premio);
        
        if(isset($data['premio']['id_premio']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_camp' => $this->input->post('id_camp'),
					'id_equipo' => $this->input->post('id_equipo'),
					'nombre_premio' => $this->input->post('nombre_premio'),
					'costo_premio' => $this->input->post('costo_premio'),
					'detalle_premio' => $this->input->post('detalle_premio'),
					'estado_premio' => $this->input->post('estado_premio'),
                );

                $this->Premio_model->update_premio($id_premio,$params);            
                redirect('premio/index');
            }
            else
            {
                $data['_view'] = 'premio/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The premio you are trying to edit does not exist.');
    } 

    /*
     * Deleting premio
     */
    function remove($id_premio)
    {
        $premio = $this->Premio_model->get_premio($id_premio);

        // check if the premio exists before trying to delete it
        if(isset($premio['id_premio']))
        {
            $this->Premio_model->delete_premio($id_premio);
            redirect('premio/index');
        }
        else
            show_error('The premio you are trying to delete does not exist.');
    }
    
}
