<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reunion_model');
    } 

    /*
     * Listing of reunion
     */
    function index()
    {
        $data['reunion'] = $this->Reunion_model->get_all_reunion();
        
        $data['_view'] = 'reunion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reunion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_camp' => $this->input->post('id_camp'),
				'fecha_reunion' => $this->input->post('fecha_reunion'),
				'ini_reunion' => $this->input->post('ini_reunion'),
				'fin_reunion' => $this->input->post('fin_reunion'),
				'detalle_reunion' => $this->input->post('detalle_reunion'),
            );
            
            $reunion_id = $this->Reunion_model->add_reunion($params);
            redirect('reunion/index');
        }
        else
        {            
            $data['_view'] = 'reunion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reunion
     */
    function edit($id_reunion)
    {   
        // check if the reunion exists before trying to edit it
        $data['reunion'] = $this->Reunion_model->get_reunion($id_reunion);
        
        if(isset($data['reunion']['id_reunion']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_camp' => $this->input->post('id_camp'),
					'fecha_reunion' => $this->input->post('fecha_reunion'),
					'ini_reunion' => $this->input->post('ini_reunion'),
					'fin_reunion' => $this->input->post('fin_reunion'),
					'detalle_reunion' => $this->input->post('detalle_reunion'),
                );

                $this->Reunion_model->update_reunion($id_reunion,$params);            
                redirect('reunion/index');
            }
            else
            {
                $data['_view'] = 'reunion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reunion you are trying to edit does not exist.');
    } 

    /*
     * Deleting reunion
     */
    function remove($id_reunion)
    {
        $reunion = $this->Reunion_model->get_reunion($id_reunion);

        // check if the reunion exists before trying to delete it
        if(isset($reunion['id_reunion']))
        {
            $this->Reunion_model->delete_reunion($id_reunion);
            redirect('reunion/index');
        }
        else
            show_error('The reunion you are trying to delete does not exist.');
    }
    
}
