<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_delegado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reunion_delegado_model');
    } 

    /*
     * Listing of reunion_delegado
     */
    function index()
    {
        $data['reunion_delegado'] = $this->Reunion_delegado_model->get_all_reunion_delegado();
        
        $data['_view'] = 'reunion_delegado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reunion_delegado
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $reunion_delegado_id = $this->Reunion_delegado_model->add_reunion_delegado($params);
            redirect('reunion_delegado/index');
        }
        else
        {            
            $data['_view'] = 'reunion_delegado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reunion_delegado
     */
    function edit($id_reunion)
    {   
        // check if the reunion_delegado exists before trying to edit it
        $data['reunion_delegado'] = $this->Reunion_delegado_model->get_reunion_delegado($id_reunion);
        
        if(isset($data['reunion_delegado']['id_reunion']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Reunion_delegado_model->update_reunion_delegado($id_reunion,$params);            
                redirect('reunion_delegado/index');
            }
            else
            {
                $data['_view'] = 'reunion_delegado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reunion_delegado you are trying to edit does not exist.');
    } 

    /*
     * Deleting reunion_delegado
     */
    function remove($id_reunion)
    {
        $reunion_delegado = $this->Reunion_delegado_model->get_reunion_delegado($id_reunion);

        // check if the reunion_delegado exists before trying to delete it
        if(isset($reunion_delegado['id_reunion']))
        {
            $this->Reunion_delegado_model->delete_reunion_delegado($id_reunion);
            redirect('reunion_delegado/index');
        }
        else
            show_error('The reunion_delegado you are trying to delete does not exist.');
    }
    
}
