<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sf_guard_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sf_guard_user_model');
    } 

    /*
     * Listing of sf_guard_user
     */
    function index()
    {
        $data['sf_guard_user'] = $this->Sf_guard_user_model->get_all_sf_guard_user();
        
        $data['_view'] = 'sf_guard_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sf_guard_user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'email_address' => $this->input->post('email_address'),
				'username' => $this->input->post('username'),
				'algorithm' => $this->input->post('algorithm'),
				'salt' => $this->input->post('salt'),
				'is_active' => $this->input->post('is_active'),
				'is_super_admin' => $this->input->post('is_super_admin'),
				'last_login' => $this->input->post('last_login'),
            );
            
            $sf_guard_user_id = $this->Sf_guard_user_model->add_sf_guard_user($params);
            redirect('sf_guard_user/index');
        }
        else
        {            
            $data['_view'] = 'sf_guard_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sf_guard_user
     */
    function edit($user_id)
    {   
        // check if the sf_guard_user exists before trying to edit it
        $data['sf_guard_user'] = $this->Sf_guard_user_model->get_sf_guard_user($user_id);
        
        if(isset($data['sf_guard_user']['user_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'email_address' => $this->input->post('email_address'),
					'username' => $this->input->post('username'),
					'algorithm' => $this->input->post('algorithm'),
					'salt' => $this->input->post('salt'),
					'is_active' => $this->input->post('is_active'),
					'is_super_admin' => $this->input->post('is_super_admin'),
					'last_login' => $this->input->post('last_login'),
                );

                $this->Sf_guard_user_model->update_sf_guard_user($user_id,$params);            
                redirect('sf_guard_user/index');
            }
            else
            {
                $data['_view'] = 'sf_guard_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sf_guard_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting sf_guard_user
     */
    function remove($user_id)
    {
        $sf_guard_user = $this->Sf_guard_user_model->get_sf_guard_user($user_id);

        // check if the sf_guard_user exists before trying to delete it
        if(isset($sf_guard_user['user_id']))
        {
            $this->Sf_guard_user_model->delete_sf_guard_user($user_id);
            redirect('sf_guard_user/index');
        }
        else
            show_error('The sf_guard_user you are trying to delete does not exist.');
    }
    
}
