<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Telefono extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Telefono_model');
    } 

    /*
     * Listing of telefono
     */
    function index()
    {
        $data['telefono'] = $this->Telefono_model->get_all_telefono();
        
        $data['_view'] = 'telefono/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new telefono
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_inf' => $this->input->post('id_inf'),
				'num_telefono' => $this->input->post('num_telefono'),
				'tipo_telefono' => $this->input->post('tipo_telefono'),
				'lugar_telefono' => $this->input->post('lugar_telefono'),
            );
            
            $telefono_id = $this->Telefono_model->add_telefono($params);
            redirect('telefono/index');
        }
        else
        {            
            $data['_view'] = 'telefono/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a telefono
     */
    function edit($id_telefono)
    {   
        // check if the telefono exists before trying to edit it
        $data['telefono'] = $this->Telefono_model->get_telefono($id_telefono);
        
        if(isset($data['telefono']['id_telefono']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_inf' => $this->input->post('id_inf'),
					'num_telefono' => $this->input->post('num_telefono'),
					'tipo_telefono' => $this->input->post('tipo_telefono'),
					'lugar_telefono' => $this->input->post('lugar_telefono'),
                );

                $this->Telefono_model->update_telefono($id_telefono,$params);            
                redirect('telefono/index');
            }
            else
            {
                $data['_view'] = 'telefono/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The telefono you are trying to edit does not exist.');
    } 

    /*
     * Deleting telefono
     */
    function remove($id_telefono)
    {
        $telefono = $this->Telefono_model->get_telefono($id_telefono);

        // check if the telefono exists before trying to delete it
        if(isset($telefono['id_telefono']))
        {
            $this->Telefono_model->delete_telefono($id_telefono);
            redirect('telefono/index');
        }
        else
            show_error('The telefono you are trying to delete does not exist.');
    }
    
}
