<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_campeonato extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_campeonato_model');
    } 

    /*
     * Listing of tipo_campeonato
     */
    function index()
    {
        $data['tipo_campeonato'] = $this->Tipo_campeonato_model->get_all_tipo_campeonato();
        
        $data['_view'] = 'tipo_campeonato/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_campeonato
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('nombre_tipo_camp','Nombre','trim|required', array('required' => 'Este Campo no debe estar vacio'));
        if($this->form_validation->run())     
        {
            $estado = "ACTIVO";
            $params = array(
                'nombre_tipo_camp' => $this->input->post('nombre_tipo_camp'),
                'estado_tipo_camp' => $estado,
            );
            
            $tipo_campeonato_id = $this->Tipo_campeonato_model->add_tipo_campeonato($params);
            redirect('tipo_campeonato/index');
        }
        else
        {            
            $data['_view'] = 'tipo_campeonato/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_campeonato
     */
    function edit($id_tipo_camp)
    {   
        // check if the tipo_campeonato exists before trying to edit it
        $data['tipo_campeonato'] = $this->Tipo_campeonato_model->get_tipo_campeonato($id_tipo_camp);
        
        if(isset($data['tipo_campeonato']['id_tipo_camp']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nombre_tipo_camp','Nombre','trim|required', array('required' => 'Este Campo no debe estar vacio'));
            if($this->form_validation->run())     
            {   
                $params = array(
                    'nombre_tipo_camp' => $this->input->post('nombre_tipo_camp'),
                    'estado_tipo_camp' => $this->input->post('estado_tipo_camp'),
                );

                $this->Tipo_campeonato_model->update_tipo_campeonato($id_tipo_camp,$params);            
                redirect('tipo_campeonato/index');
            }
            else
            {
                $data['_view'] = 'tipo_campeonato/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_campeonato you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_campeonato
     */
    /*function remove($id_tipo_camp)
    {
        $tipo_campeonato = $this->Tipo_campeonato_model->get_tipo_campeonato($id_tipo_camp);

        // check if the tipo_campeonato exists before trying to delete it
        if(isset($tipo_campeonato['id_tipo_camp']))
        {
            $this->Tipo_campeonato_model->delete_tipo_campeonato($id_tipo_camp);
            redirect('tipo_campeonato/index');
        }
        else
            show_error('The tipo_campeonato you are trying to delete does not exist.');
    }*/
    
}
