<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Uniforme extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Uniforme_model');
    } 

    /*
     * Listing of uniforme
     */
    function index()
    {
        $data['uniforme'] = $this->Uniforme_model->get_all_uniforme();
        
        $data['_view'] = 'uniforme/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new uniforme
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_equipo' => $this->input->post('id_equipo'),
				'casaca_unif' => $this->input->post('casaca_unif'),
				'pant_corto_unif' => $this->input->post('pant_corto_unif'),
				'medias_unif' => $this->input->post('medias_unif'),
				'imagen_unif' => $this->input->post('imagen_unif'),
            );
            
            $uniforme_id = $this->Uniforme_model->add_uniforme($params);
            redirect('uniforme/index');
        }
        else
        {            
            $data['_view'] = 'uniforme/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a uniforme
     */
    function edit($id_unif)
    {   
        // check if the uniforme exists before trying to edit it
        $data['uniforme'] = $this->Uniforme_model->get_uniforme($id_unif);
        
        if(isset($data['uniforme']['id_unif']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_equipo' => $this->input->post('id_equipo'),
					'casaca_unif' => $this->input->post('casaca_unif'),
					'pant_corto_unif' => $this->input->post('pant_corto_unif'),
					'medias_unif' => $this->input->post('medias_unif'),
					'imagen_unif' => $this->input->post('imagen_unif'),
                );

                $this->Uniforme_model->update_uniforme($id_unif,$params);            
                redirect('uniforme/index');
            }
            else
            {
                $data['_view'] = 'uniforme/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The uniforme you are trying to edit does not exist.');
    } 

    /*
     * Deleting uniforme
     */
    function remove($id_unif)
    {
        $uniforme = $this->Uniforme_model->get_uniforme($id_unif);

        // check if the uniforme exists before trying to delete it
        if(isset($uniforme['id_unif']))
        {
            $this->Uniforme_model->delete_uniforme($id_unif);
            redirect('uniforme/index');
        }
        else
            show_error('The uniforme you are trying to delete does not exist.');
    }
    
}
