<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arbitro_planilla_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get arbitro_planilla by id_arbitro
     */
    function get_arbitro_planilla($id_arbitro)
    {
        return $this->db->get_where('arbitro_planilla',array('id_arbitro'=>$id_arbitro))->row_array();
    }
        
    /*
     * Get all arbitro_planilla
     */
    function get_all_arbitro_planilla()
    {
        $this->db->order_by('id_arbitro', 'desc');
        return $this->db->get('arbitro_planilla')->result_array();
    }
        
    /*
     * function to add new arbitro_planilla
     */
    function add_arbitro_planilla($params)
    {
        $this->db->insert('arbitro_planilla',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update arbitro_planilla
     */
    function update_arbitro_planilla($id_arbitro,$params)
    {
        $this->db->where('id_arbitro',$id_arbitro);
        return $this->db->update('arbitro_planilla',$params);
    }
    
    /*
     * function to delete arbitro_planilla
     */
    function delete_arbitro_planilla($id_arbitro)
    {
        return $this->db->delete('arbitro_planilla',array('id_arbitro'=>$id_arbitro));
    }
}
