<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arbitro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get arbitro by id_arbitro
     */
    function get_arbitro($id_arbitro)
    {
        return $this->db->get_where('arbitro',array('id_arbitro'=>$id_arbitro))->row_array();
    }
        
    /*
     * Get all arbitro
     */
    function get_all_arbitro()
    {
        $this->db->order_by('id_arbitro', 'desc');
        return $this->db->get('arbitro')->result_array();
    }
        
    /*
     * function to add new arbitro
     */
    function add_arbitro($params)
    {
        $this->db->insert('arbitro',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update arbitro
     */
    function update_arbitro($id_arbitro,$params)
    {
        $this->db->where('id_arbitro',$id_arbitro);
        return $this->db->update('arbitro',$params);
    }
    
    /*
     * function to delete arbitro
     */
    function delete_arbitro($id_arbitro)
    {
        return $this->db->delete('arbitro',array('id_arbitro'=>$id_arbitro));
    }
}
