<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Campeonato_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campeonato by id_camp
     */
    function get_campeonato($id_camp)
    {
        return $this->db->get_where('campeonato',array('id_camp'=>$id_camp))->row_array();
    }
        
    /*
     * Get all campeonato
     */
    function get_all_campeonato()
    {
        $this->db->order_by('id_camp', 'desc');
        return $this->db->get('campeonato')->result_array();
    }
        
    /*
     * function to add new campeonato
     */
    function add_campeonato($params)
    {
        $this->db->insert('campeonato',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campeonato
     */
    function update_campeonato($id_camp,$params)
    {
        $this->db->where('id_camp',$id_camp);
        return $this->db->update('campeonato',$params);
    }
    
    /*
     * function to delete campeonato
     */
    function delete_campeonato($id_camp)
    {
        return $this->db->delete('campeonato',array('id_camp'=>$id_camp));
    }
}
