<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Club_deportivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get club_deportivo by id_club
     */
    function get_club_deportivo($id_club)
    {
        return $this->db->get_where('club_deportivo',array('id_club'=>$id_club))->row_array();
    }
        
    /*
     * Get all club_deportivo
     */
    function get_all_club_deportivo()
    {
        $this->db->order_by('id_club', 'desc');
        return $this->db->get('club_deportivo')->result_array();
    }
        
    /*
     * function to add new club_deportivo
     */
    function add_club_deportivo($params)
    {
        $this->db->insert('club_deportivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update club_deportivo
     */
    function update_club_deportivo($id_club,$params)
    {
        $this->db->where('id_club',$id_club);
        return $this->db->update('club_deportivo',$params);
    }
    
    /*
     * function to delete club_deportivo
     */
    function delete_club_deportivo($id_club)
    {
        return $this->db->delete('club_deportivo',array('id_club'=>$id_club));
    }
}
