<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Delegado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get delegado by id_delegado
     */
    function get_delegado($id_delegado)
    {
        return $this->db->get_where('delegado',array('id_delegado'=>$id_delegado))->row_array();
    }
        
    /*
     * Get all delegado
     */
    function get_all_delegado()
    {
        $this->db->order_by('id_delegado', 'desc');
        return $this->db->get('delegado')->result_array();
    }
        
    /*
     * function to add new delegado
     */
    function add_delegado($params)
    {
        $this->db->insert('delegado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update delegado
     */
    function update_delegado($id_delegado,$params)
    {
        $this->db->where('id_delegado',$id_delegado);
        return $this->db->update('delegado',$params);
    }
    
    /*
     * function to delete delegado
     */
    function delete_delegado($id_delegado)
    {
        return $this->db->delete('delegado',array('id_delegado'=>$id_delegado));
    }
}
