<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Email_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get email by id_email
     */
    function get_email($id_email)
    {
        return $this->db->get_where('email',array('id_email'=>$id_email))->row_array();
    }
        
    /*
     * Get all email
     */
    function get_all_email()
    {
        $this->db->order_by('id_email', 'desc');
        return $this->db->get('email')->result_array();
    }
        
    /*
     * function to add new email
     */
    function add_email($params)
    {
        $this->db->insert('email',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update email
     */
    function update_email($id_email,$params)
    {
        $this->db->where('id_email',$id_email);
        return $this->db->update('email',$params);
    }
    
    /*
     * function to delete email
     */
    function delete_email($id_email)
    {
        return $this->db->delete('email',array('id_email'=>$id_email));
    }
}
