<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrenador_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get entrenador by id_entrenador
     */
    function get_entrenador($id_entrenador)
    {
        return $this->db->get_where('entrenador',array('id_entrenador'=>$id_entrenador))->row_array();
    }
        
    /*
     * Get all entrenador
     */
    function get_all_entrenador()
    {
        $this->db->order_by('id_entrenador', 'desc');
        return $this->db->get('entrenador')->result_array();
    }
        
    /*
     * function to add new entrenador
     */
    function add_entrenador($params)
    {
        $this->db->insert('entrenador',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update entrenador
     */
    function update_entrenador($id_entrenador,$params)
    {
        $this->db->where('id_entrenador',$id_entrenador);
        return $this->db->update('entrenador',$params);
    }
    
    /*
     * function to delete entrenador
     */
    function delete_entrenador($id_entrenador)
    {
        return $this->db->delete('entrenador',array('id_entrenador'=>$id_entrenador));
    }
}
