<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipo_jugador_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get equipo_jugador by id_jug_equipo
     */
    function get_equipo_jugador($id_jug_equipo)
    {
        return $this->db->get_where('equipo_jugador',array('id_jug_equipo'=>$id_jug_equipo))->row_array();
    }
        
    /*
     * Get all equipo_jugador
     */
    function get_all_equipo_jugador()
    {
        $this->db->order_by('id_jug_equipo', 'desc');
        return $this->db->get('equipo_jugador')->result_array();
    }
        
    /*
     * function to add new equipo_jugador
     */
    function add_equipo_jugador($params)
    {
        $this->db->insert('equipo_jugador',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update equipo_jugador
     */
    function update_equipo_jugador($id_jug_equipo,$params)
    {
        $this->db->where('id_jug_equipo',$id_jug_equipo);
        return $this->db->update('equipo_jugador',$params);
    }
    
    /*
     * function to delete equipo_jugador
     */
    function delete_equipo_jugador($id_jug_equipo)
    {
        return $this->db->delete('equipo_jugador',array('id_jug_equipo'=>$id_jug_equipo));
    }
}
