<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gestion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gestion by id_gestion
     */
    function get_gestion($id_gestion)
    {
        return $this->db->get_where('gestion',array('id_gestion'=>$id_gestion))->row_array();
    }
        
    /*
     * Get all gestion
     */
    function get_all_gestion()
    {
        $this->db->order_by('id_gestion', 'desc');
        return $this->db->get('gestion')->result_array();
    }
        
    /*
     * function to add new gestion
     */
    function add_gestion($params)
    {
        $this->db->insert('gestion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gestion
     */
    function update_gestion($id_gestion,$params)
    {
        $this->db->where('id_gestion',$id_gestion);
        return $this->db->update('gestion',$params);
    }
    
    /*
     * function to delete gestion
     */
    function delete_gestion($id_gestion)
    {
        return $this->db->delete('gestion',array('id_gestion'=>$id_gestion));
    }
}
