<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jug_gol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jug_gol by id_jug_gol
     */
    function get_jug_gol($id_jug_gol)
    {
        return $this->db->get_where('jug_gol',array('id_jug_gol'=>$id_jug_gol))->row_array();
    }
        
    /*
     * Get all jug_gol
     */
    function get_all_jug_gol()
    {
        $this->db->order_by('id_jug_gol', 'desc');
        return $this->db->get('jug_gol')->result_array();
    }
        
    /*
     * function to add new jug_gol
     */
    function add_jug_gol($params)
    {
        $this->db->insert('jug_gol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jug_gol
     */
    function update_jug_gol($id_jug_gol,$params)
    {
        $this->db->where('id_jug_gol',$id_jug_gol);
        return $this->db->update('jug_gol',$params);
    }
    
    /*
     * function to delete jug_gol
     */
    function delete_jug_gol($id_jug_gol)
    {
        return $this->db->delete('jug_gol',array('id_jug_gol'=>$id_jug_gol));
    }
}
