<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jugador_planilla_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jugador_planilla by id_jugador_planilla
     */
    function get_jugador_planilla($id_jugador_planilla)
    {
        return $this->db->get_where('jugador_planilla',array('id_jugador_planilla'=>$id_jugador_planilla))->row_array();
    }
        
    /*
     * Get all jugador_planilla
     */
    function get_all_jugador_planilla()
    {
        $this->db->order_by('id_jugador_planilla', 'desc');
        return $this->db->get('jugador_planilla')->result_array();
    }
        
    /*
     * function to add new jugador_planilla
     */
    function add_jugador_planilla($params)
    {
        $this->db->insert('jugador_planilla',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jugador_planilla
     */
    function update_jugador_planilla($id_jugador_planilla,$params)
    {
        $this->db->where('id_jugador_planilla',$id_jugador_planilla);
        return $this->db->update('jugador_planilla',$params);
    }
    
    /*
     * function to delete jugador_planilla
     */
    function delete_jugador_planilla($id_jugador_planilla)
    {
        return $this->db->delete('jugador_planilla',array('id_jugador_planilla'=>$id_jugador_planilla));
    }
}
