<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jugador_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jugador by id_jug
     */
    function get_jugador($id_jug)
    {
        return $this->db->get_where('jugador',array('id_jug'=>$id_jug))->row_array();
    }
        
    /*
     * Get all jugador
     */
    function get_all_jugador()
    {
        $this->db->order_by('id_jug', 'desc');
        return $this->db->get('jugador')->result_array();
    }
        
    /*
     * function to add new jugador
     */
    function add_jugador($params)
    {
        $this->db->insert('jugador',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jugador
     */
    function update_jugador($id_jug,$params)
    {
        $this->db->where('id_jug',$id_jug);
        return $this->db->update('jugador',$params);
    }
    
    /*
     * function to delete jugador
     */
    function delete_jugador($id_jug)
    {
        return $this->db->delete('jugador',array('id_jug'=>$id_jug));
    }
}
