<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Memorandum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get memorandum by id_memo
     */
    function get_memorandum($id_memo)
    {
        return $this->db->get_where('memorandum',array('id_memo'=>$id_memo))->row_array();
    }
        
    /*
     * Get all memorandum
     */
    function get_all_memorandum()
    {
        $this->db->order_by('id_memo', 'desc');
        return $this->db->get('memorandum')->result_array();
    }
        
    /*
     * function to add new memorandum
     */
    function add_memorandum($params)
    {
        $this->db->insert('memorandum',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update memorandum
     */
    function update_memorandum($id_memo,$params)
    {
        $this->db->where('id_memo',$id_memo);
        return $this->db->update('memorandum',$params);
    }
    
    /*
     * function to delete memorandum
     */
    function delete_memorandum($id_memo)
    {
        return $this->db->delete('memorandum',array('id_memo'=>$id_memo));
    }
}
