<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa_directiva_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mesa_directiva by id_mesa
     */
    function get_mesa_directiva($id_mesa)
    {
        return $this->db->get_where('mesa_directiva',array('id_mesa'=>$id_mesa))->row_array();
    }
        
    /*
     * Get all mesa_directiva
     */
    function get_all_mesa_directiva()
    {
        $this->db->order_by('id_mesa', 'desc');
        return $this->db->get('mesa_directiva')->result_array();
    }
        
    /*
     * function to add new mesa_directiva
     */
    function add_mesa_directiva($params)
    {
        $this->db->insert('mesa_directiva',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mesa_directiva
     */
    function update_mesa_directiva($id_mesa,$params)
    {
        $this->db->where('id_mesa',$id_mesa);
        return $this->db->update('mesa_directiva',$params);
    }
    
    /*
     * function to delete mesa_directiva
     */
    function delete_mesa_directiva($id_mesa)
    {
        return $this->db->delete('mesa_directiva',array('id_mesa'=>$id_mesa));
    }
}
