<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Movimiento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get movimiento by id_mov
     */
    function get_movimiento($id_mov)
    {
        return $this->db->get_where('movimiento',array('id_mov'=>$id_mov))->row_array();
    }
        
    /*
     * Get all movimiento
     */
    function get_all_movimiento()
    {
        $this->db->order_by('id_mov', 'desc');
        return $this->db->get('movimiento')->result_array();
    }
        
    /*
     * function to add new movimiento
     */
    function add_movimiento($params)
    {
        $this->db->insert('movimiento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update movimiento
     */
    function update_movimiento($id_mov,$params)
    {
        $this->db->where('id_mov',$id_mov);
        return $this->db->update('movimiento',$params);
    }
    
    /*
     * function to delete movimiento
     */
    function delete_movimiento($id_mov)
    {
        return $this->db->delete('movimiento',array('id_mov'=>$id_mov));
    }
}
