<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Noticium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get noticium by id_not
     */
    function get_noticium($id_not)
    {
        return $this->db->get_where('noticia',array('id_not'=>$id_not))->row_array();
    }
        
    /*
     * Get all noticia
     */
    function get_all_noticia()
    {
        $this->db->order_by('id_not', 'desc');
        return $this->db->get('noticia')->result_array();
    }
        
    /*
     * function to add new noticium
     */
    function add_noticium($params)
    {
        $this->db->insert('noticia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update noticium
     */
    function update_noticium($id_not,$params)
    {
        $this->db->where('id_not',$id_not);
        return $this->db->update('noticia',$params);
    }
    
    /*
     * function to delete noticium
     */
    function delete_noticium($id_not)
    {
        return $this->db->delete('noticia',array('id_not'=>$id_not));
    }
}
