<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Planilla_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get planilla by id_plan
     */
    function get_planilla($id_plan)
    {
        return $this->db->get_where('planilla',array('id_plan'=>$id_plan))->row_array();
    }
        
    /*
     * Get all planilla
     */
    function get_all_planilla()
    {
        $this->db->order_by('id_plan', 'desc');
        return $this->db->get('planilla')->result_array();
    }
        
    /*
     * function to add new planilla
     */
    function add_planilla($params)
    {
        $this->db->insert('planilla',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update planilla
     */
    function update_planilla($id_plan,$params)
    {
        $this->db->where('id_plan',$id_plan);
        return $this->db->update('planilla',$params);
    }
    
    /*
     * function to delete planilla
     */
    function delete_planilla($id_plan)
    {
        return $this->db->delete('planilla',array('id_plan'=>$id_plan));
    }
}
