<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Premio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get premio by id_premio
     */
    function get_premio($id_premio)
    {
        return $this->db->get_where('premio',array('id_premio'=>$id_premio))->row_array();
    }
        
    /*
     * Get all premio
     */
    function get_all_premio()
    {
        $this->db->order_by('id_premio', 'desc');
        return $this->db->get('premio')->result_array();
    }
        
    /*
     * function to add new premio
     */
    function add_premio($params)
    {
        $this->db->insert('premio',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update premio
     */
    function update_premio($id_premio,$params)
    {
        $this->db->where('id_premio',$id_premio);
        return $this->db->update('premio',$params);
    }
    
    /*
     * function to delete premio
     */
    function delete_premio($id_premio)
    {
        return $this->db->delete('premio',array('id_premio'=>$id_premio));
    }
}
