<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion by id_reunion
     */
    function get_reunion($id_reunion)
    {
        return $this->db->get_where('reunion',array('id_reunion'=>$id_reunion))->row_array();
    }
        
    /*
     * Get all reunion
     */
    function get_all_reunion()
    {
        $this->db->order_by('id_reunion', 'desc');
        return $this->db->get('reunion')->result_array();
    }
        
    /*
     * function to add new reunion
     */
    function add_reunion($params)
    {
        $this->db->insert('reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion
     */
    function update_reunion($id_reunion,$params)
    {
        $this->db->where('id_reunion',$id_reunion);
        return $this->db->update('reunion',$params);
    }
    
    /*
     * function to delete reunion
     */
    function delete_reunion($id_reunion)
    {
        return $this->db->delete('reunion',array('id_reunion'=>$id_reunion));
    }
}
