<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_delegado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion_delegado by id_reunion
     */
    function get_reunion_delegado($id_reunion)
    {
        return $this->db->get_where('reunion_delegado',array('id_reunion'=>$id_reunion))->row_array();
    }
        
    /*
     * Get all reunion_delegado
     */
    function get_all_reunion_delegado()
    {
        $this->db->order_by('id_reunion', 'desc');
        return $this->db->get('reunion_delegado')->result_array();
    }
        
    /*
     * function to add new reunion_delegado
     */
    function add_reunion_delegado($params)
    {
        $this->db->insert('reunion_delegado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion_delegado
     */
    function update_reunion_delegado($id_reunion,$params)
    {
        $this->db->where('id_reunion',$id_reunion);
        return $this->db->update('reunion_delegado',$params);
    }
    
    /*
     * function to delete reunion_delegado
     */
    function delete_reunion_delegado($id_reunion)
    {
        return $this->db->delete('reunion_delegado',array('id_reunion'=>$id_reunion));
    }
}
