<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Telefono_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get telefono by id_telefono
     */
    function get_telefono($id_telefono)
    {
        return $this->db->get_where('telefono',array('id_telefono'=>$id_telefono))->row_array();
    }
        
    /*
     * Get all telefono
     */
    function get_all_telefono()
    {
        $this->db->order_by('id_telefono', 'desc');
        return $this->db->get('telefono')->result_array();
    }
        
    /*
     * function to add new telefono
     */
    function add_telefono($params)
    {
        $this->db->insert('telefono',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update telefono
     */
    function update_telefono($id_telefono,$params)
    {
        $this->db->where('id_telefono',$id_telefono);
        return $this->db->update('telefono',$params);
    }
    
    /*
     * function to delete telefono
     */
    function delete_telefono($id_telefono)
    {
        return $this->db->delete('telefono',array('id_telefono'=>$id_telefono));
    }
}
