<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Uniforme_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get uniforme by id_unif
     */
    function get_uniforme($id_unif)
    {
        return $this->db->get_where('uniforme',array('id_unif'=>$id_unif))->row_array();
    }
        
    /*
     * Get all uniforme
     */
    function get_all_uniforme()
    {
        $this->db->order_by('id_unif', 'desc');
        return $this->db->get('uniforme')->result_array();
    }
        
    /*
     * function to add new uniforme
     */
    function add_uniforme($params)
    {
        $this->db->insert('uniforme',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update uniforme
     */
    function update_uniforme($id_unif,$params)
    {
        $this->db->where('id_unif',$id_unif);
        return $this->db->update('uniforme',$params);
    }
    
    /*
     * function to delete uniforme
     */
    function delete_uniforme($id_unif)
    {
        return $this->db->delete('uniforme',array('id_unif'=>$id_unif));
    }
}
