<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by id_usuario
     */
    function get_usuario($id_usuario)
    {
        return $this->db->get_where('usuario',array('id_usuario'=>$id_usuario))->row_array();
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $this->db->select('u.*, tu.descripcion_tipousuario');
        $this->db->from('usuario u');
        $this->db->join('tipo_usuario tu', 'tu.id_tipousuario = u.id_tipousuario', 'left');
        $this->db->order_by('u.id_usuario', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($id_usuario,$params)
    {
        $this->db->where('id_usuario',$id_usuario);
        return $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($id_usuario)
    {
        return $this->db->delete('usuario',array('id_usuario'=>$id_usuario));
    }
    public function hay_login1($login)
    {
        $this->db->select('id_usuario');
        $this->db->from('usuario');
        $this->db->where('login_usuario', $login);
        //$var = $this->db->last_query();
        //return $var;
        $query = $this->db->get();
        if ( $query->num_rows() > 0 ){
            return 1; // si hay
        } else {
            return 0; // no hay
        }
    }
    
    public function email_repeat2($email,$idu)
    {
        $this->db->select('id_usuario');
        $this->db->from('usuario');
        $this->db->where('email_usuario', $email);
        $this->db->where('id_usuario !=', $idu);
        $query = $this->db->get();
        if ( $query->num_rows() > 0 ){
            //$row = $query->row_array();
            return true;
        }else{
            return false;
        }
    }

    public function login_repeat2($login, $uid)
    {
        $this->db->select('id_usuario');
        $this->db->from('usuario');
        $this->db->where('id_usuario !=', $uid);
        $this->db->where('login_usuario', $login);
        //$var = $this->db->last_query();
        //return $var;
        $query = $this->db->get();
        if ( $query->num_rows() > 0 ){
            return true; // si hay
        } else {
            return false; // no hay
        }
    }
}
